-- ==========================================================================
-- Esquema del "mainframe" legacy simulado (H2).
-- Spring Boot ejecuta este schema.sql automaticamente al arrancar
-- (ver spring.sql.init en application.yml).
--
-- DROP + CREATE para que cada arranque parta de un estado limpio y conocido:
-- al ser una BD en memoria, se recrea en cada ejecucion.
-- ==========================================================================

DROP TABLE IF EXISTS MOVIMIENTO;
DROP TABLE IF EXISTS CUENTA;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CLIENTE (
    id         BIGINT       PRIMARY KEY,
    nombre     VARCHAR(120) NOT NULL,
    documento  VARCHAR(20)  NOT NULL
);

CREATE TABLE CUENTA (
    id             BIGINT        PRIMARY KEY,
    cliente_id     BIGINT        NOT NULL,
    numero_cuenta  VARCHAR(24)   NOT NULL,
    tipo           VARCHAR(20)   NOT NULL,   -- AHORRO, CORRIENTE...
    saldo          DECIMAL(15,2) NOT NULL,
    moneda         VARCHAR(3)    NOT NULL,   -- PEN, USD...
    estado         VARCHAR(15)   NOT NULL,   -- ACTIVA, BLOQUEADA...
    CONSTRAINT fk_cuenta_cliente FOREIGN KEY (cliente_id) REFERENCES CLIENTE (id)
);

CREATE TABLE MOVIMIENTO (
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id   BIGINT        NOT NULL,
    tipo        VARCHAR(10)   NOT NULL,   -- CARGO, ABONO, INTERES
    monto       DECIMAL(15,2) NOT NULL,
    descripcion VARCHAR(200)  NOT NULL,
    fecha       TIMESTAMP     NOT NULL,
    CONSTRAINT fk_movimiento_cuenta FOREIGN KEY (cuenta_id) REFERENCES CUENTA (id)
);
